---
- hosts: 172.31.8.44
  become: yes
  tasks:
  - name: i want to install git
    apt:
     name: git
     state: present
    tags: mygit

  - name: install tree
    apt: 
     name: tree
     state: present
    tags: mytree

  - name: install wget
    apt:
     name: wget
     state: present
    tags: mywget